const data = {
    products: [
        {
            _id: '1',
            name: 'Планшет-коробка на 100 стекол',
            slug: 'Планшет',
            category: 'Планшеты',
            image: 'frontend/public/images/Фото1.jpg',
            prise: '1 шт/уп',
            number: '31012100AO',
            countInStock: 16,
            brand: 'Citotest Labware Manufacturing',
            country: 'Китай',
        },
        {
            _id: '2',
            name: 'Стекло покровное, 24х50 мм',
            slug: 'Стекло',
            category: 'Стекла',
            image: 'frontend/public/images/Фото2.jpeg',
            prise: '200 шт/уп',
            number: '2404',
            countInStock: 13,
            brand: 'ООО "ЭргоПродакшн"',
            country: 'Россия',
        },
        {
            _id: '3',
            name: 'Кассеты для биопсии',
            slug: 'Кассеты',
            category: 'Кассеты для биопсии',
            image: 'frontend/public/images/Фото3.jpg',
            prise: '500 шт/уп',
            number: '70195',
            countInStock: 10,
            brand: 'DiaPath',
            country: 'Италия',
        },
        {
            _id: '4',
            name: 'Твин-20',
            slug: 'Твин',
            category: 'Химия',
            image: 'frontend/public/images/Фото4.jpg',
            prise: '100 мл',
            number: '51601',
            countInStock: 0,
            brand: 'FERAK',
            country: 'Германия',
        },
    ],
};
export default data;
